### ISSUE TITLE
pcloudpy breaks on startup

### ISSUE THREAD

**Issue by smfloery** [mmolero/pcloudpy#1]
When starting pcloudpy running "python main.py" it breaks:

/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Populating the interactive namespace from numpy and matplotlib
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    app.run()
  File "/home/sfloery/GIT/pcloudpy/pcloudpy/gui/app.py", line 27, in run
    win = MainWindow()
  File "/home/sfloery/GIT/pcloudpy/pcloudpy/gui/MainWindow.py", line 26, in __init__
    super(MainWindow, self).__init__(parent)
  File "/home/sfloery/GIT/pcloudpy/pcloudpy/gui/MainWindowBase.py", line 64, in __init__
    self.init_toolboxes()
  File "/home/sfloery/GIT/pcloudpy/pcloudpy/gui/MainWindowBase.py", line 290, in init_toolboxes
    with open(os.path.join(path,'resources\conf\config_toolboxes.yaml'), 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/sfloery/GIT/pcloudpy/pcloudpy/gui/resources\\conf\\config_toolboxes.yaml'
QProcess: Destroyed while process is still running.

Problem is, that the path is created using windows path separator; as I'm using Linux the separator is different; changing 
with open(os.path.join(path,'resources\conf\config_toolboxes.yaml'), 'r') as f:
to
with open(os.path.join(path,'resources', 'conf', 'config_toolboxes.yaml'), 'r') as f:
prevents this failure

**Comment by mmolero** [comment]
Thank
Could you please make a pull request in order to add the suggested changes
Thanks!!
